app.port: '8080'
generate.routes: 'false'
log.level: info
log.text: 'false'
in.memory: 'false'
db:
  host: postgres-service
  port: '5432'
  user: postgres
  pass: postgres
  name: smfg-db
  migrate: 'false'
queue:
  host: rabbitmq-service
  port: '5672'
  user: smfg-inventory
  pass: smfg-inventory
  name: inventory